[project]
name = "academicwritingtutor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "William Kwako", email = "wkwakow@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "django>=6.1.1",
    "langchain-anthropic>=1.7.1",
    "langchain-core>=1.6.2",
    "langchain-openai>=1.6.0",
    "langgraph>=1.2.11",
    "python-dotenv>=1.2.3",
]

[project.scripts]
academicwritingtutor = "academicwritingtutor:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
